locale: 'pt'

backend:
  name: git-gateway
  branch: main

display_url: https://wogofilmes.com.br/
logo_url: https://raw.githubusercontent.com/buenavistalab/buena-vista-lab/master/assets/t1.png

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: _data/blog
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { name: title, label: Título, widget: string, required: false }
      - { name: img, label: Imagem, widget: image, required: false }
      - { name: body, label: Body, widget: markdown, required: false }
      - { name: vimeo, label: Vimeo, widget: markdown, required: false }
  # - name: convencoes
  #   label: Convencoes
  #   folder: _data/convencoes
  #   slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - {
  #         label: Template,
  #         name: template,
  #         widget: hidden,
  #         default: ConvencoesPost,
  #       }
  #     - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY" }
  #     - { name: name, label: Nome, widget: string }
  #     - { name: arquivo, label: Arquivo, widget: file }
