locale: 'pt'

backend:
  name: git-gateway
  branch: main

display_url: https://wogofilmes.com.br/
logo_url: https://wogofilmes.com.br/static/logos/logo.jpg

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Projeto
    folder: _data/blog
    slug: '{{day}}-{{month}}-{{year}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          name: template,
          label: Template,
          widget: hidden,
          default: BlogPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { name: title, label: Título, widget: string, required: false }
      - { name: img, label: Imagem, widget: image, required: false }
      - { name: body, label: Texto, widget: markdown, required: false }
      - { name: vimeo, label: Vimeo, widget: markdown, required: false }
      - {
          name: featured,
          label: Destaque na home,
          widget: select,
          required: false,
          options: ['img', 'vimeo']
        }
